# Site settings
title:       Ben Johnston
email:       ben.e.johnston@gmail.com
author:      Ben Johnston
description: "Designer, Engineer. Based in California, available around the globe."
baseurl:     ""
url:         "http://ben-johnston.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
